# Generated by Django 5.2.11 on 2026-03-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_update_site_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('question_ru', models.CharField(max_length=255, null=True, verbose_name='Вопрос')),
                ('question_uk', models.CharField(max_length=255, null=True, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('answer_ru', models.TextField(null=True, verbose_name='Ответ')),
                ('answer_uk', models.TextField(null=True, verbose_name='Ответ')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Вопрос-ответ',
                'verbose_name_plural': 'FAQ (Вопросы-ответы)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FAQSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Частые вопросы', max_length=120, verbose_name='Заголовок секции')),
                ('title_ru', models.CharField(default='Частые вопросы', max_length=120, null=True, verbose_name='Заголовок секции')),
                ('title_uk', models.CharField(default='Частые вопросы', max_length=120, null=True, verbose_name='Заголовок секции')),
            ],
            options={
                'verbose_name': 'Секция FAQ',
                'verbose_name_plural': 'Секция FAQ',
            },
        ),
        migrations.DeleteModel(
            name='AuctionSection',
        ),
        migrations.AlterModelOptions(
            name='aboutsection',
            options={'verbose_name': 'Секция «О нас»', 'verbose_name_plural': 'Секция «О нас»'},
        ),
        migrations.AlterModelOptions(
            name='advantageitem',
            options={'ordering': ['order'], 'verbose_name': 'Преимущество', 'verbose_name_plural': 'Преимущества'},
        ),
        migrations.AlterModelOptions(
            name='advantagessection',
            options={'verbose_name': 'Секция «Преимущества»', 'verbose_name_plural': 'Секция «Преимущества»'},
        ),
        migrations.AlterModelOptions(
            name='contactsection',
            options={'verbose_name': 'Секция «Контакты»', 'verbose_name_plural': 'Секция «Контакты»'},
        ),
        migrations.AlterModelOptions(
            name='herosection',
            options={'verbose_name': 'Hero-секция', 'verbose_name_plural': 'Hero-секция'},
        ),
        migrations.AlterModelOptions(
            name='serviceitem',
            options={'ordering': ['category', 'order'], 'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterModelOptions(
            name='servicessection',
            options={'verbose_name': 'Секция «Услуги»', 'verbose_name_plural': 'Секция «Услуги»'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Настройки сайта', 'verbose_name_plural': 'Настройки сайта'},
        ),
        migrations.AlterModelOptions(
            name='statitem',
            options={'ordering': ['order'], 'verbose_name': 'Статистика', 'verbose_name_plural': 'Статистика (цифры)'},
        ),
        migrations.AlterModelOptions(
            name='workstep',
            options={'ordering': ['order'], 'verbose_name': 'Шаг работы', 'verbose_name_plural': 'Этапы работы'},
        ),
        migrations.RemoveField(
            model_name='leadsubmission',
            name='interest',
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='philosophy_text_ru',
            field=models.TextField(default='Чип-тюнинг — это оптимизация заводской прошивки ЭБУ двигателя.', null=True, verbose_name='Текст описания'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='philosophy_text_uk',
            field=models.TextField(default='Чип-тюнинг — это оптимизация заводской прошивки ЭБУ двигателя.', null=True, verbose_name='Текст описания'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='philosophy_title_ru',
            field=models.CharField(default='Раскройте потенциал вашего двигателя', max_length=160, null=True, verbose_name='Заголовок подблока'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='philosophy_title_uk',
            field=models.CharField(default='Раскройте потенциал вашего двигателя', max_length=160, null=True, verbose_name='Заголовок подблока'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='title_ru',
            field=models.CharField(default='Что такое чип-тюнинг?', max_length=120, null=True, verbose_name='Заголовок секции'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='title_uk',
            field=models.CharField(default='Что такое чип-тюнинг?', max_length=120, null=True, verbose_name='Заголовок секции'),
        ),
        migrations.AddField(
            model_name='advantageitem',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='advantageitem',
            name='description_uk',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='advantageitem',
            name='title_ru',
            field=models.CharField(max_length=120, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='advantageitem',
            name='title_uk',
            field=models.CharField(max_length=120, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='advantagessection',
            name='footer_quote_ru',
            field=models.TextField(default='Мы не бросаем в трудной ситуации.', null=True, verbose_name='Цитата внизу блока'),
        ),
        migrations.AddField(
            model_name='advantagessection',
            name='footer_quote_uk',
            field=models.TextField(default='Мы не бросаем в трудной ситуации.', null=True, verbose_name='Цитата внизу блока'),
        ),
        migrations.AddField(
            model_name='advantagessection',
            name='subtitle_ru',
            field=models.CharField(default='Качество, поддержка и индивидуальный подход.', max_length=200, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='advantagessection',
            name='subtitle_uk',
            field=models.CharField(default='Качество, поддержка и индивидуальный подход.', max_length=200, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='advantagessection',
            name='title_ru',
            field=models.CharField(default='Почему выбирают нас?', max_length=120, null=True, verbose_name='Заголовок секции'),
        ),
        migrations.AddField(
            model_name='advantagessection',
            name='title_uk',
            field=models.CharField(default='Почему выбирают нас?', max_length=120, null=True, verbose_name='Заголовок секции'),
        ),
        migrations.AddField(
            model_name='contactsection',
            name='description_ru',
            field=models.TextField(default='Оставьте заявку — мы перезвоним в кратчайшее время.', null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='contactsection',
            name='description_uk',
            field=models.TextField(default='Оставьте заявку — мы перезвоним в кратчайшее время.', null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='contactsection',
            name='form_btn_text_ru',
            field=models.CharField(default='ОТПРАВИТЬ', max_length=80, null=True, verbose_name='Текст кнопки формы'),
        ),
        migrations.AddField(
            model_name='contactsection',
            name='form_btn_text_uk',
            field=models.CharField(default='ОТПРАВИТЬ', max_length=80, null=True, verbose_name='Текст кнопки формы'),
        ),
        migrations.AddField(
            model_name='contactsection',
            name='form_title_ru',
            field=models.CharField(default='Оставить заявку', max_length=120, null=True, verbose_name='Заголовок формы'),
        ),
        migrations.AddField(
            model_name='contactsection',
            name='form_title_uk',
            field=models.CharField(default='Оставить заявку', max_length=120, null=True, verbose_name='Заголовок формы'),
        ),
        migrations.AddField(
            model_name='contactsection',
            name='privacy_note_ru',
            field=models.CharField(default='Ваши данные в безопасности. Мы гарантируем конфиденциальность.', max_length=200, null=True, verbose_name='Прим. конфиденциальности'),
        ),
        migrations.AddField(
            model_name='contactsection',
            name='privacy_note_uk',
            field=models.CharField(default='Ваши данные в безопасности. Мы гарантируем конфиденциальность.', max_length=200, null=True, verbose_name='Прим. конфиденциальности'),
        ),
        migrations.AddField(
            model_name='contactsection',
            name='title_ru',
            field=models.CharField(default='Свяжитесь с нами', max_length=120, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='contactsection',
            name='title_uk',
            field=models.CharField(default='Свяжитесь с нами', max_length=120, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='btn_buy_text_ru',
            field=models.CharField(default='Получить консультацию', max_length=60, null=True, verbose_name='Текст кнопки 1'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='btn_buy_text_uk',
            field=models.CharField(default='Получить консультацию', max_length=60, null=True, verbose_name='Текст кнопки 1'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='btn_sell_text_ru',
            field=models.CharField(default='Наши услуги', max_length=60, null=True, verbose_name='Текст кнопки 2'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='btn_sell_text_uk',
            field=models.CharField(default='Наши услуги', max_length=60, null=True, verbose_name='Текст кнопки 2'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='subtitle_ru',
            field=models.TextField(default='Профессиональный чип-тюнинг и калибровка ЭБУ.', null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='subtitle_uk',
            field=models.TextField(default='Профессиональный чип-тюнинг и калибровка ЭБУ.', null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='title_ru',
            field=models.CharField(default='БЫСТРЕЕ. МОЩНЕЕ. ЭКОНОМИЧНЕЕ.', max_length=120, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='title_uk',
            field=models.CharField(default='БЫСТРЕЕ. МОЩНЕЕ. ЭКОНОМИЧНЕЕ.', max_length=120, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='leadsubmission',
            name='message',
            field=models.TextField(blank=True, default='', verbose_name='Сообщение'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='description_uk',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='icon_key',
            field=models.CharField(blank=True, choices=[('filter', 'Фильтр (DPF/FAP)'), ('recycle', 'Рециркуляция (EGR)'), ('droplet', 'Мочевина (AdBlue)'), ('gauge', 'Датчик (Lambda/CAT)'), ('wind', 'Заслонки (Flaps/TVA)'), ('alert', 'Ошибки (DTC)'), ('engine', 'Двигатель'), ('speed', 'Мощность (Stage)'), ('wrench', 'Настройка')], default='engine', max_length=20, verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='title_ru',
            field=models.CharField(max_length=120, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='title_uk',
            field=models.CharField(max_length=120, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='servicessection',
            name='steps_title_ru',
            field=models.CharField(default='Как мы работаем', max_length=160, null=True, verbose_name='Заголовок блока шагов'),
        ),
        migrations.AddField(
            model_name='servicessection',
            name='steps_title_uk',
            field=models.CharField(default='Как мы работаем', max_length=160, null=True, verbose_name='Заголовок блока шагов'),
        ),
        migrations.AddField(
            model_name='servicessection',
            name='title_ru',
            field=models.CharField(default='Наши услуги', max_length=120, null=True, verbose_name='Заголовок секции'),
        ),
        migrations.AddField(
            model_name='servicessection',
            name='title_uk',
            field=models.CharField(default='Наши услуги', max_length=120, null=True, verbose_name='Заголовок секции'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_uk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='call_btn_text_ru',
            field=models.CharField(default='Получить консультацию', max_length=60, null=True, verbose_name='Текст кнопки звонка'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='call_btn_text_uk',
            field=models.CharField(default='Получить консультацию', max_length=60, null=True, verbose_name='Текст кнопки звонка'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='statitem',
            name='label_ru',
            field=models.CharField(max_length=120, null=True, verbose_name='Подпись'),
        ),
        migrations.AddField(
            model_name='statitem',
            name='label_uk',
            field=models.CharField(max_length=120, null=True, verbose_name='Подпись'),
        ),
        migrations.AddField(
            model_name='statitem',
            name='value_ru',
            field=models.CharField(max_length=40, null=True, verbose_name='Значение'),
        ),
        migrations.AddField(
            model_name='statitem',
            name='value_uk',
            field=models.CharField(max_length=40, null=True, verbose_name='Значение'),
        ),
        migrations.AddField(
            model_name='workstep',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='workstep',
            name='description_uk',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='workstep',
            name='title_ru',
            field=models.CharField(max_length=160, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='workstep',
            name='title_uk',
            field=models.CharField(max_length=160, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='philosophy_text',
            field=models.TextField(default='Чип-тюнинг — это оптимизация заводской прошивки ЭБУ двигателя.', verbose_name='Текст описания'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='philosophy_title',
            field=models.CharField(default='Раскройте потенциал вашего двигателя', max_length=160, verbose_name='Заголовок подблока'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='title',
            field=models.CharField(default='Что такое чип-тюнинг?', max_length=120, verbose_name='Заголовок секции'),
        ),
        migrations.AlterField(
            model_name='advantageitem',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='advantageitem',
            name='icon_key',
            field=models.CharField(choices=[('shield', 'Щит (безопасность)'), ('chart', 'График (выгода)'), ('clock', 'Часы (опыт)'), ('key', 'Ключ (под ключ)'), ('eye', 'Глаз (мониторинг)'), ('checkmark', 'Галочка (гарантия)'), ('star', 'Звезда'), ('map', 'Карта'), ('engine', 'Двигатель'), ('speed', 'Спидометр'), ('fuel', 'Топливо'), ('wrench', 'Гаечный ключ'), ('power', 'Молния (мощность)'), ('headset', 'Поддержка')], default='shield', max_length=20, verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='advantagessection',
            name='footer_quote',
            field=models.TextField(default='Мы не бросаем в трудной ситуации.', verbose_name='Цитата внизу блока'),
        ),
        migrations.AlterField(
            model_name='advantagessection',
            name='subtitle',
            field=models.CharField(default='Качество, поддержка и индивидуальный подход.', max_length=200, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='advantagessection',
            name='title',
            field=models.CharField(default='Почему выбирают нас?', max_length=120, verbose_name='Заголовок секции'),
        ),
        migrations.AlterField(
            model_name='contactsection',
            name='description',
            field=models.TextField(default='Оставьте заявку — мы перезвоним в кратчайшее время.', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='contactsection',
            name='form_btn_text',
            field=models.CharField(default='ОТПРАВИТЬ', max_length=80, verbose_name='Текст кнопки формы'),
        ),
        migrations.AlterField(
            model_name='contactsection',
            name='form_title',
            field=models.CharField(default='Оставить заявку', max_length=120, verbose_name='Заголовок формы'),
        ),
        migrations.AlterField(
            model_name='contactsection',
            name='privacy_note',
            field=models.CharField(default='Ваши данные в безопасности. Мы гарантируем конфиденциальность.', max_length=200, verbose_name='Прим. конфиденциальности'),
        ),
        migrations.AlterField(
            model_name='contactsection',
            name='title',
            field=models.CharField(default='Свяжитесь с нами', max_length=120, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='Фоновое изображение'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='btn_buy_text',
            field=models.CharField(default='Получить консультацию', max_length=60, verbose_name='Текст кнопки 1'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='btn_sell_text',
            field=models.CharField(default='Наши услуги', max_length=60, verbose_name='Текст кнопки 2'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='overlay_opacity',
            field=models.FloatField(default=0.7, verbose_name='Прозрачность оверлея (0–1)'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='subtitle',
            field=models.TextField(default='Профессиональный чип-тюнинг и калибровка ЭБУ.', verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='title',
            field=models.CharField(default='БЫСТРЕЕ. МОЩНЕЕ. ЭКОНОМИЧНЕЕ.', max_length=120, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='leadsubmission',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='Обработано'),
        ),
        migrations.AlterField(
            model_name='leadsubmission',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='category',
            field=models.CharField(choices=[('removal', 'Удаление систем'), ('tuning', 'Настройка мощности')], max_length=10, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='servicessection',
            name='steps_title',
            field=models.CharField(default='Как мы работаем', max_length=160, verbose_name='Заголовок блока шагов'),
        ),
        migrations.AlterField(
            model_name='servicessection',
            name='title',
            field=models.CharField(default='Наши услуги', max_length=120, verbose_name='Заголовок секции'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='call_btn_text',
            field=models.CharField(default='Получить консультацию', max_length=60, verbose_name='Текст кнопки звонка'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(default='distageavto@gmail.com', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(default='+38095-073-41-18', max_length=30, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='statitem',
            name='label',
            field=models.CharField(max_length=120, verbose_name='Подпись'),
        ),
        migrations.AlterField(
            model_name='statitem',
            name='value',
            field=models.CharField(max_length=40, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='workstep',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='workstep',
            name='is_highlighted',
            field=models.BooleanField(default=False, verbose_name='Выделить (акцент)'),
        ),
        migrations.AlterField(
            model_name='workstep',
            name='number',
            field=models.PositiveSmallIntegerField(verbose_name='Номер шага'),
        ),
    ]
