# Generated by manually (simulating makemigrations)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_fix_stat_label_uk'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=80, verbose_name='Автор')),
                ('car', models.CharField(blank=True, max_length=80, verbose_name='Авто')),
                ('text', models.TextField(verbose_name='Текст відгуку')),
                ('text_ru', models.TextField(null=True, verbose_name='Текст відгуку')),
                ('text_uk', models.TextField(null=True, verbose_name='Текст відгуку')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Відгук',
                'verbose_name_plural': 'Відгуки',
                'ordering': ['order'],
            },
        ),
    ]
