# Generated by Django 5.2.11 on 2026-04-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_partneritem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partneritem',
            name='logo',
            field=models.ImageField(blank=True, upload_to='partners/', verbose_name='Логотип'),
        ),
    ]
